version: '3.4'

networks:
  polygon:
      driver: bridge

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    networks:
      - polygon
    ports:
      - "5672:5672" # RabbitMQ
    restart: unless-stopped
  
  heimdalld:
    container_name: heimdalld
    image: heimdall:latest
    build: ../../heimdall
    restart: unless-stopped
    networks:
      - polygon
    volumes:
      - /ethereum/heimdall:/root/.heimdalld
    ports:
      - "26656:26656" # P2P (TCP)
      - "26657:26657" # RPC (TCP)
    depends_on:
      - rabbitmq
    command:
      - heimdalld
      - start
      - --moniker=ambolt-node
      - --p2p.laddr=tcp://0.0.0.0:26656
      - --rpc.laddr=tcp://0.0.0.0:26657

  heimdallr:
    container_name: heimdallr
    image: heimdall:latest
    build: ../../heimdall
    restart: unless-stopped
    networks:
      - polygon
    volumes:
      - /ethereum/heimdall:/root/.heimdalld
    ports:
      - "1317:1317" # Heimdall REST API
    depends_on:
      - heimdalld
    command:
      - heimdalld
      - rest-server
      - --chain-id=137
      - --laddr=tcp://0.0.0.0:1317
      - --node=tcp://heimdalld:26657
  
  bor:
    container_name: bor
    image: bor:latest
    build: ../../bor
    restart: unless-stopped
    networks:
      - polygon
    volumes:
        - /ethereum/bor:/datadir
    ports:
        - "8549:8545" # RPC
        - "30307:30303" # Peers (TCP)
        - "30307:30303/udp" # Peers (UDP)
    command:
        - bor
        - --syncmode=full
        - --datadir=/datadir
        - --networkid=137
        - --bor.heimdall=http://heimdallr:1317
        - --miner.gaslimit=200000000
        - --miner.gastarget=20000000
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --http.api=eth,net,web3,admin,debug,bor
        - --http.corsdomain=*
        - --http.vhosts=*
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=8545
        - --ws.api=eth,net,web3,admin,debug,bor
        - --ws.origins=*        
        - --nousb
        - --bootnodes=enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303

    

      